Anonymous:
    label: Anonymous
    handler: Anonymous
    type: anon

User:
    label: User Login
    handler: User NoAuth
    type: passwd

Operator:
    label: Operator Login
    handler: Operator Password
    type: passwd

Testing:
    label: Test Accounts
    handler: TestAccounts
    type: passwd

OTP:
    label: OneTimePassword
    handler: OneTimePassword
    type: passwd
    param:
        label: I18N_OPENXPKI_UI_OTP_LOGIN_LABEL
        description: I18N_OPENXPKI_UI_OTP_LOGIN_DESC
        button: I18N_OPENXPKI_UI_OTP_LOGIN_BUTTON
        field:
          - name: token
            label: I18N_OPENXPKI_UI_LOGIN_TOKEN
            type: password

Certificate:
    label: Client certificate
    handler: Certificate
    type: x509
    sign:
        # This is the public key matching the private one given in webui/default.conf
        # Use "openssl pkey -pubout" to create the required string from the private key
        # key: MFkwEwYHK.......pK7qV/FmDw==

_System:
    handler: System
